(* generated by dune *)

(** @canonical Async_log_kernel.Buffered_output *)
module Buffered_output = Async_log_kernel__Buffered_output

(** @canonical Async_log_kernel.Global *)
module Global = Async_log_kernel__Global

(** @canonical Async_log_kernel.Global_intf *)
module Global_intf = Async_log_kernel__Global_intf

(** @canonical Async_log_kernel.Import *)
module Import = Async_log_kernel__Import

(** @canonical Async_log_kernel.Level *)
module Level = Async_log_kernel__Level

(** @canonical Async_log_kernel.Live_entry_registry *)
module Live_entry_registry = Async_log_kernel__Live_entry_registry

(** @canonical Async_log_kernel.Log *)
module Log = Async_log_kernel__Log

(** @canonical Async_log_kernel.Message *)
module Message = Async_log_kernel__Message

(** @canonical Async_log_kernel.Message_event *)
module Message_event = Async_log_kernel__Message_event

(** @canonical Async_log_kernel.Mutable_outputs *)
module Mutable_outputs = Async_log_kernel__Mutable_outputs

(** @canonical Async_log_kernel.On_error *)
module On_error = Async_log_kernel__On_error

(** @canonical Async_log_kernel.Output *)
module Output = Async_log_kernel__Output

(** @canonical Async_log_kernel.Output_format *)
module Output_format = Async_log_kernel__Output_format

(** @canonical Async_log_kernel.Ppx_log_syntax *)
module Ppx_log_syntax = Async_log_kernel__Ppx_log_syntax

(** @canonical Async_log_kernel.Raw_log *)
module Raw_log = Async_log_kernel__Raw_log

(** @canonical Async_log_kernel.Sexp_or_string *)
module Sexp_or_string = Async_log_kernel__Sexp_or_string

(** @canonical Async_log_kernel.Versioned *)
module Versioned = Async_log_kernel__Versioned

(** @canonical Async_log_kernel.Versioned_intf *)
module Versioned_intf = Async_log_kernel__Versioned_intf

module Async_log_kernel__ = struct end
[@@deprecated "this module is shadowed"]
