(* generated by dune *)

(** @canonical Async_unix.Async_print *)
module Async_print = Async_unix__Async_print

(** @canonical Async_unix.Async_sys *)
module Async_sys = Async_unix__Async_sys

(** @canonical Async_unix.Backing_out_channel *)
module Backing_out_channel = Async_unix__Backing_out_channel

(** @canonical Async_unix.Busy_poller *)
module Busy_poller = Async_unix__Busy_poller

(** @canonical Async_unix.Busy_poller_intf *)
module Busy_poller_intf = Async_unix__Busy_poller_intf

(** @canonical Async_unix.By_descr *)
module By_descr = Async_unix__By_descr

(** @canonical Async_unix.Clock *)
module Clock = Async_unix__Clock

(** @canonical Async_unix.Config *)
module Config = Async_unix__Config

(** @canonical Async_unix.Dump_core_on_job_delay *)
module Dump_core_on_job_delay = Async_unix__Dump_core_on_job_delay

(** @canonical Async_unix.Epoll_file_descr_watcher *)
module Epoll_file_descr_watcher = Async_unix__Epoll_file_descr_watcher

(** @canonical Async_unix.Fd *)
module Fd = Async_unix__Fd

(** @canonical Async_unix.File_descr_watcher_intf *)
module File_descr_watcher_intf = Async_unix__File_descr_watcher_intf

(** @canonical Async_unix.Import *)
module Import = Async_unix__Import

(** @canonical Async_unix.In_thread *)
module In_thread = Async_unix__In_thread

(** @canonical Async_unix.Interruptor *)
module Interruptor = Async_unix__Interruptor

(** @canonical Async_unix.Io_stats *)
module Io_stats = Async_unix__Io_stats

(** @canonical Async_unix.Io_uring *)
module Io_uring = Async_unix__Io_uring

(** @canonical Async_unix.Io_uring_file_descr_watcher *)
module Io_uring_file_descr_watcher = Async_unix__Io_uring_file_descr_watcher

(** @canonical Async_unix.Io_uring_raw *)
module Io_uring_raw = Async_unix__Io_uring_raw

(** @canonical Async_unix.Io_uring_raw_intf *)
module Io_uring_raw_intf = Async_unix__Io_uring_raw_intf

(** @canonical Async_unix.Io_uring_raw_null *)
module Io_uring_raw_null = Async_unix__Io_uring_raw_null

(** @canonical Async_unix.Io_uring_raw_singleton *)
module Io_uring_raw_singleton = Async_unix__Io_uring_raw_singleton

(** @canonical Async_unix.Io_uring_types_intf *)
module Io_uring_types_intf = Async_unix__Io_uring_types_intf

(** @canonical Async_unix.Process *)
module Process = Async_unix__Process

(** @canonical Async_unix.Raw_fd *)
module Raw_fd = Async_unix__Raw_fd

(** @canonical Async_unix.Raw_scheduler *)
module Raw_scheduler = Async_unix__Raw_scheduler

(** @canonical Async_unix.Raw_signal_manager *)
module Raw_signal_manager = Async_unix__Raw_signal_manager

(** @canonical Async_unix.Reader *)
module Reader = Async_unix__Reader

(** @canonical Async_unix.Reader0 *)
module Reader0 = Async_unix__Reader0

(** @canonical Async_unix.Require_explicit_time_source *)
module Require_explicit_time_source = Async_unix__Require_explicit_time_source

(** @canonical Async_unix.Require_explicit_time_source_intf *)
module Require_explicit_time_source_intf = Async_unix__Require_explicit_time_source_intf

(** @canonical Async_unix.Scheduler *)
module Scheduler = Async_unix__Scheduler

(** @canonical Async_unix.Select_file_descr_watcher *)
module Select_file_descr_watcher = Async_unix__Select_file_descr_watcher

(** @canonical Async_unix.Shutdown *)
module Shutdown = Async_unix__Shutdown

(** @canonical Async_unix.Signal *)
module Signal = Async_unix__Signal

(** @canonical Async_unix.Signal_manager *)
module Signal_manager = Async_unix__Signal_manager

(** @canonical Async_unix.Syscall *)
module Syscall = Async_unix__Syscall

(** @canonical Async_unix.Tcp *)
module Tcp = Async_unix__Tcp

(** @canonical Async_unix.Thread_safe *)
module Thread_safe = Async_unix__Thread_safe

(** @canonical Async_unix.Time_source_tests *)
module Time_source_tests = Async_unix__Time_source_tests

(** @canonical Async_unix.Unix_syscalls *)
module Unix_syscalls = Async_unix__Unix_syscalls

(** @canonical Async_unix.Unused *)
module Unused = Async_unix__Unused

(** @canonical Async_unix.Writer *)
module Writer = Async_unix__Writer

(** @canonical Async_unix.Writer0 *)
module Writer0 = Async_unix__Writer0

(** @canonical Async_unix.Writer_intf *)
module Writer_intf = Async_unix__Writer_intf

module Async_unix__ = struct end
[@@deprecated "this module is shadowed"]
