(* generated by dune *)

(** @canonical Async_log.Assign_top_level_logs *)
module Assign_top_level_logs = Async_log__Assign_top_level_logs

(** @canonical Async_log.Blocking *)
module Blocking = Async_log__Blocking

(** @canonical Async_log.Import *)
module Import = Async_log__Import

(** @canonical Async_log.Import_stable *)
module Import_stable = Async_log__Import_stable

(** @canonical Async_log.Log *)
module Log = Async_log__Log

(** @canonical Async_log.Message *)
module Message = Async_log__Message

(** @canonical Async_log.Message_reader *)
module Message_reader = Async_log__Message_reader

(** @canonical Async_log.Output *)
module Output = Async_log__Output

(** @canonical Async_log.Rotation *)
module Rotation = Async_log__Rotation

(** @canonical Async_log.Rotation_id *)
module Rotation_id = Async_log__Rotation_id

(** @canonical Async_log.Rotation_id_intf *)
module Rotation_id_intf = Async_log__Rotation_id_intf

module Async_log__ = struct end
[@@deprecated "this module is shadowed"]
