(* generated by dune *)

(** @canonical Async.Deferred_or_error_expect_test_config *)
module Deferred_or_error_expect_test_config = Async__Deferred_or_error_expect_test_config

(** @canonical Async.Expect_test_config *)
module Expect_test_config = Async__Expect_test_config

(** @canonical Async.Expect_test_config_or_error *)
module Expect_test_config_or_error = Async__Expect_test_config_or_error

module Async__ = struct end
[@@deprecated "this module is shadowed"]
