(* generated by dune *)

(** @canonical Async_quickcheck.Async_quickcheck_intf *)
module Async_quickcheck_intf = Async_quickcheck__Async_quickcheck_intf

module Async_quickcheck__ = struct end
[@@deprecated "this module is shadowed"]
