(* generated by dune *)

(** @canonical Eager_deferred.Eager_deferred0 *)
module Eager_deferred0 = Eager_deferred__Eager_deferred0

(** @canonical Eager_deferred.Eager_deferred1 *)
module Eager_deferred1 = Eager_deferred__Eager_deferred1

(** @canonical Eager_deferred.Eager_deferred_intf *)
module Eager_deferred_intf = Eager_deferred__Eager_deferred_intf

(** @canonical Eager_deferred.Eager_deferred_list *)
module Eager_deferred_list = Eager_deferred__Eager_deferred_list

(** @canonical Eager_deferred.Eager_deferred_memo *)
module Eager_deferred_memo = Eager_deferred__Eager_deferred_memo

(** @canonical Eager_deferred.Eager_deferred_or_error *)
module Eager_deferred_or_error = Eager_deferred__Eager_deferred_or_error

(** @canonical Eager_deferred.Eager_deferred_queue *)
module Eager_deferred_queue = Eager_deferred__Eager_deferred_queue

(** @canonical Eager_deferred.Eager_deferred_result *)
module Eager_deferred_result = Eager_deferred__Eager_deferred_result

(** @canonical Eager_deferred.Import *)
module Import = Eager_deferred__Import

module Eager_deferred__ = struct end
[@@deprecated "this module is shadowed"]
