(* generated by dune *)

(** @canonical Persistent_connection_kernel.Event *)
module Event = Persistent_connection_kernel__Event

(** @canonical Persistent_connection_kernel.Persistent_connection_kernel_intf *)
module Persistent_connection_kernel_intf = Persistent_connection_kernel__Persistent_connection_kernel_intf

module Persistent_connection_kernel__ = struct end
[@@deprecated "this module is shadowed"]
