(* generated by dune *)

(** @canonical Persistent_connection.Import *)
module Import = Persistent_connection__Import

(** @canonical Persistent_connection.Persistent_connection_intf *)
module Persistent_connection_intf = Persistent_connection__Persistent_connection_intf

module Persistent_connection__ = struct end
[@@deprecated "this module is shadowed"]
